version: "3"
services:
  redis-server:
    image: redis:6.0-alpine
  mongodb:
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
  flask:
    build:
      context: ./python_keras/
      dockerfile: ./flask/Dockerfile #continuation of above path
    env_file: ./python_keras/flask/flask.env
    ports:
      - 5000:80
    depends_on:
      - redis-server
      - mongodb
      - celery
  celery:
    build: ./python_keras/celery
    env_file: ./python_keras/celery/celery.env
    ports:
      - 5555:5555
    depends_on:
      - redis-server
      - mongodb
  node:
    build: ./node
    env_file: ./node/node.env
    environment:
      - NPM_TEST=true
    ports:
      - 4000:4000
    depends_on:
      - mongodb
      - flask
